# #######################################################################################
### CORE ###
source = ./core/variables.conf
source = ./core/autostart.conf
source = ./core/environment.conf
source = ./core/permission.conf
source = ./core/keybindings.conf

### APPERANCE ###
source = ./appearance/windowrule.conf
source = ./appearance/lookNfeel.conf
source = ./appearance/animation.conf

### IO ###
source = ./io/monitor.conf
source = ./io/input.conf




